use spacetimedb_codegen::{generate, CodegenOptions, Csharp, Rust, TypeScript};
use spacetimedb_data_structures::map::HashMap;
use spacetimedb_schema::def::ModuleDef;
use spacetimedb_testing::modules::{CompilationMode, CompiledModule};
use std::sync::OnceLock;

fn compiled_module() -> &'static ModuleDef {
    static COMPILED_MODULE: OnceLock<ModuleDef> = OnceLock::new();
    COMPILED_MODULE
        .get_or_init(|| CompiledModule::compile("module-test", CompilationMode::Debug).extract_schema_blocking())
}

macro_rules! declare_tests {
    ($($name:ident => $lang:expr,)*) => ($(
        #[test]
        fn $name() {
            let module = compiled_module();
            let outfiles = generate(&module, &$lang, &CodegenOptions::default())
                .into_iter()
                .map(|f| (f.filename, f.code))
                .collect::<HashMap<_, _>>();
            let mut settings = insta::Settings::clone_current();
            settings.set_sort_maps(true);
            // Ignore the autogenerated comments with version info, since it changes with every
            // build.
            settings.add_filter(r"// This was generated using spacetimedb cli version \d+\.\d+\.\d+ .*", "VERSION_COMMENT");
            // Ignore the place where the CLI version is put in the typescript REMOTE_MODULE info,
            // so it isn't constantly changing.
            settings.add_filter(r#"cliVersion: "\d+\.\d+\.\d+","#, r#"cliVersion: "X.Y.Z","#);
            settings.bind(|| {
                insta::assert_toml_snapshot!(outfiles);
            });
        }
    )*);
}

declare_tests! {
    test_codegen_csharp => Csharp { namespace: "SpacetimeDB" },
    test_codegen_typescript => TypeScript,
    test_codegen_rust => Rust,
}

#[test]
fn test_typescript_table_handles_are_camel_case() {
    let module = compiled_module();
    let index = generate(module, &TypeScript, &CodegenOptions::default())
        .into_iter()
        .find(|file| file.filename == "index.ts")
        .expect("typescript codegen should emit index.ts")
        .code;

    assert!(index.contains("loggedOutPlayer: __table({"));
    assert!(!index.contains("logged_out_player: __table({"));
    assert!(index.contains("myPlayer: __table({"));
    assert!(!index.contains("my_player: __table({"));
    assert!(index.contains(r#""logged_out_player": "loggedOutPlayer""#));
    assert!(index.contains(r#"readonly "logged_out_player": __TablesBase["loggedOutPlayer"];"#));
    assert!(index.contains(r#"readonly "logged_out_player": __DbViewBase["loggedOutPlayer"];"#));
    assert!(index.contains(
        r#"/** @deprecated Use `loggedOutPlayer` instead. This alias will be removed in the next major version. */"#
    ));
}

/// A submodule reducer's wire name must be qualified exactly once.
///
/// `ReducerDef::name` is fully qualified, so any code that also prepends the namespace
/// path would emit `lib.lib.libInsert`. Nothing in the snapshot fixtures mounts a
/// submodule, so this checks the TypeScript output of one that does.
#[test]
fn submodule_reducer_wire_name_is_qualified_once() {
    let module = CompiledModule::compile("module-test-ts", CompilationMode::Debug).extract_schema_blocking();
    let code = generate(&module, &TypeScript, &CodegenOptions::default())
        .into_iter()
        .map(|f| f.code)
        .collect::<Vec<_>>()
        .join("\n");

    let reducer_lines: Vec<_> = code.lines().filter(|l| l.contains("__reducerSchema(")).collect();
    assert!(
        code.contains(r#"__reducerSchema("lib.lib_insert""#),
        "expected a singly-qualified wire name for the submodule reducer; got:\n{}",
        reducer_lines.join("\n")
    );
    assert!(
        !code.contains("lib.lib."),
        "namespace was applied twice somewhere in the generated bindings"
    );
}

/// Client codegen must not emit an accessor for a vector index.
///
/// Every backend reaches an index through `IndexAlgorithm::columns()` and emits a typed
/// key lookup. A vector index has no key — it ranks whole embeddings by distance, which is
/// answered by the host inside a transaction and has no client-side equivalent. Emitting
/// one anyway produced C# that does not compile, because `BTreeIndexBase<T>` requires the
/// key type to be `IEquatable` and `IComparable`, and `List<float>` is neither.
#[test]
fn vector_indexes_are_not_exposed_to_clients() {
    use spacetimedb_lib::db::raw_def::v9::{
        btree, RawIndexAlgorithm, RawModuleDefV9Builder, RawVectorIndexV9, RawVectorMetric, RawVectorStrategy,
    };
    use spacetimedb_lib::{AlgebraicType, ProductType};

    let mut builder = RawModuleDefV9Builder::new();
    builder
        .build_table_with_new_type(
            "Document",
            ProductType::from([
                ("id", AlgebraicType::U64),
                ("embedding", AlgebraicType::array(AlgebraicType::F32)),
            ]),
            true,
        )
        .with_index(btree(0), "by_id")
        .with_index(
            RawIndexAlgorithm::Vector(RawVectorIndexV9 {
                column: 1.into(),
                dimension: 4,
                metric: RawVectorMetric::Cosine,
                strategy: RawVectorStrategy::Exact,
            }),
            "by_embedding",
        )
        .finish();
    let module: ModuleDef = builder
        .finish()
        .try_into()
        .expect("a table with a vector index should be a valid module");

    let generate_all = |lang_files: Vec<spacetimedb_codegen::OutputFile>| -> String {
        lang_files.into_iter().map(|f| f.code).collect()
    };

    // Each backend names accessors in its own convention, so the expectation differs.
    // Rust's client codegen emits no index accessors at all today, so it has nothing to
    // check beyond the absence of the vector one.
    let cases: [(&str, String, Option<&str>); 3] = [
        (
            "csharp",
            generate_all(generate(
                &module,
                &Csharp {
                    namespace: "SpacetimeDB",
                },
                &CodegenOptions::default(),
            )),
            Some("ById"),
        ),
        (
            "typescript",
            generate_all(generate(&module, &TypeScript, &CodegenOptions::default())),
            Some("by_id"),
        ),
        (
            "rust",
            generate_all(generate(&module, &Rust, &CodegenOptions::default())),
            None,
        ),
    ];

    for (lang, code, keyed_accessor) in cases {
        for spelling in ["by_embedding", "byEmbedding", "ByEmbedding"] {
            assert!(
                !code.contains(spelling),
                "{lang} codegen exposed the vector index as `{spelling}`"
            );
        }
        // Also assert the keyed index on the same table still comes through, so this test
        // fails if index generation breaks altogether rather than just skipping vector ones.
        if let Some(accessor) = keyed_accessor {
            assert!(
                code.contains(accessor),
                "{lang} codegen dropped the btree index too; expected `{accessor}`"
            );
        }
    }
}
