// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Internal
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RawHnswParamsV9
    {
        [DataMember(Name = "m")]
        public ushort M;
        [DataMember(Name = "ef_construction")]
        public ushort EfConstruction;
        [DataMember(Name = "ef_search")]
        public ushort EfSearch;

        public RawHnswParamsV9(
            ushort M,
            ushort EfConstruction,
            ushort EfSearch
        )
        {
            this.M = M;
            this.EfConstruction = EfConstruction;
            this.EfSearch = EfSearch;
        }

        public RawHnswParamsV9()
        {
        }
    }
}
