// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Internal
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RawVectorIndexV9
    {
        [DataMember(Name = "column")]
        public ushort Column;
        [DataMember(Name = "dimension")]
        public uint Dimension;
        [DataMember(Name = "metric")]
        public RawVectorMetric Metric;
        [DataMember(Name = "strategy")]
        public RawVectorStrategy Strategy;

        public RawVectorIndexV9(
            ushort Column,
            uint Dimension,
            RawVectorMetric Metric,
            RawVectorStrategy Strategy
        )
        {
            this.Column = Column;
            this.Dimension = Dimension;
            this.Metric = Metric;
            this.Strategy = Strategy;
        }

        public RawVectorIndexV9()
        {
            this.Strategy = null!;
        }
    }
}
