// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;

namespace SpacetimeDB.Internal
{
    [SpacetimeDB.Type]
    public partial record RawVectorStrategy : SpacetimeDB.TaggedEnum<(
        SpacetimeDB.Unit Exact,
        RawHnswParamsV9 Hnsw
    )>;
}
