// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "../autogen_base.h"
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDB::Internal {

SPACETIMEDB_INTERNAL_PRODUCT_TYPE(RawHnswParamsV9) {
    uint16_t m;
    uint16_t ef_construction;
    uint16_t ef_search;

    void bsatn_serialize(::SpacetimeDB::bsatn::Writer& writer) const {
        ::SpacetimeDB::bsatn::serialize(writer, m);
        ::SpacetimeDB::bsatn::serialize(writer, ef_construction);
        ::SpacetimeDB::bsatn::serialize(writer, ef_search);
    }
    SPACETIMEDB_PRODUCT_TYPE_EQUALITY(m, ef_construction, ef_search)
};
} // namespace SpacetimeDB::Internal
