// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "../autogen_base.h"
#include "spacetimedb/bsatn/bsatn.h"
#include "RawVectorMetric.g.h"
#include "RawVectorStrategy.g.h"

namespace SpacetimeDB::Internal {

SPACETIMEDB_INTERNAL_PRODUCT_TYPE(RawVectorIndexV9) {
    uint16_t column;
    uint32_t dimension;
    SpacetimeDB::Internal::RawVectorMetric metric;
    SpacetimeDB::Internal::RawVectorStrategy strategy;

    void bsatn_serialize(::SpacetimeDB::bsatn::Writer& writer) const {
        ::SpacetimeDB::bsatn::serialize(writer, column);
        ::SpacetimeDB::bsatn::serialize(writer, dimension);
        ::SpacetimeDB::bsatn::serialize(writer, metric);
        ::SpacetimeDB::bsatn::serialize(writer, strategy);
    }
    SPACETIMEDB_PRODUCT_TYPE_EQUALITY(column, dimension, metric, strategy)
};
} // namespace SpacetimeDB::Internal
