[package]
name = "vector-search"
version = "0.0.0"
edition.workspace = true
license-file = "LICENSE"

[lib]
crate-type = ["cdylib"]
# Benching off, because of https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
spacetimedb = { path = "../../crates/bindings" }

log.workspace = true
